Only Cleanup
lanwen/wiremock-junit5 pull request #13
Opened 2018-12-14 15:51 UTC by vp-stage

cleanup && organize imports

2018-12-27 17:52 UTC, vp-stage commented
Hey @lanwen, 
you could be interested by this PR.

Kind regards

2018-12-28 10:16 UTC, lanwen commented on src/test/java/ru/lanwen/wiremock/testlib/TicketEndpoint.java
> +        String testMethodName = context.getTestMethod().orElseThrow(IllegalStateException::new).getName();
doesn't make any sense to replace one with another

2018-12-28 10:16 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/ext/WiremockResolver.java
> -        if (server == null || !server.isRunning()) {
fail fast is preferrable

2018-12-28 10:17 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/ext/WiremockResolver.java
> +    protected WireMockServer server;
👍

2018-12-28 10:17 UTC, lanwen requested changes
star imports are banned, `final` doesn't add any value, fail fast is preferrable

2019-01-07 19:09 UTC, vp-stage commented
Hey @lanwen,
the requested changes are done :)

2019-02-04 15:26 UTC, closed without merging