Refactored WiremockCustomizer to take a Customizable object as argument
lanwen/wiremock-junit5 pull request #6
Opened 2018-04-05 21:16 UTC by SourcePond

- Introduced a parameter object which additionally provides ExtensionContext and ParameterContext beside the WireMockServer instance. This allows to implement more sophisticated setup logic based on the execution context.
- Allow to throw an exception from WiremockCustomizer::customize
- Added Unit-Tests
- Updated dependencies and plugin versions where possible
- Bumped version to 2.0.0-SNAPSHOT because the interface change

2018-04-15 21:42 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/config/WiremockConfigFactory.java
> + * You can createServer custom config to init wiremock server in test.
seems like refactoring artifact

2018-04-15 22:06 UTC, lanwen requested changes
Hey, thanks a lot for your interest and such a great idea!

But let's simplify some things and save backwards compatibility.

So as I understand, the main point is to add junit5 context to customizer.

This can be done by simple default method

```java
default void customize(final WireMockServer server, CustomizationContext ctx) throws Exception {
    customize(server);
}
```

where `CustomizationContext` is simple class with `ExtensionContext` and `ParameterContext` fields and a builder provided by lombok.

So we can just call new method without new interfaces and this complex logic around customizable which wraps server and should be created by factory...where the only place where we use all the setters is Resolver.

So it allows us to not touch a lot of code with same result

2018-04-15 22:06 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/config/WiremockCustomizer.java
> + * Helps to createServer reusable customizer for injected wiremock server
here too

2018-04-15 22:06 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/ext/WiremockFactory.java
> +                    format("Can't createServer config with given factory %s", mockedServer.factory()),
here too - just "create"

2018-04-15 22:06 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/ext/WiremockResolver.java
> +        } catch (final Exception e) {
why it should be final?

2018-04-15 22:06 UTC, lanwen commented on src/main/java/ru/lanwen/wiremock/ext/WiremockResolver.java
> +         * @return class which defines on how to createServer config
⬆️

2018-04-17 08:27 UTC, SourcePond commented
Thank you for the review! I made all the changes you suggested, but, I will open a new pull-request which summarizes all changes into one commit.

2018-04-17 08:27 UTC, closed without merging